const states = new Map([
    ["Alabama", "AL"],
    ["Alaska", "AK"],
    ["Arizona", "AZ"],
    ["Arkansas", "AR"],
    ["California", "CA"],
    ["Colorado", "CO"],
    ["Connecticut", "CT"],
    ["Delaware", "DE"],
    ["Florida", "FL"],
    ["Georgia", "GA"],
    ["Hawaii", "HI"],
    ["Idaho", "ID"],
    ["Illinois", "IL"],
    ["Indiana", "IN"],
    ["Iowa", "IA"],
    ["Kansas", "KS"],
    ["Kentucky", "KY"],
    ["Louisiana", "LA"],
    ["Maine", "ME"],
    ["Maryland", "MD"],
    ["Massachusetts", "MA"],
    ["Michigan", "MI"],
    ["Minnesota", "MN"],
    ["Mississippi", "MS"],
    ["Missouri", "MO"],
    ["Montana", "MT"],
    ["Nebraska", "NE"],
    ["Nevada", "NV"],
    ["New Hampshire", "NH"],
    ["New Jersey", "NJ"],
    ["New Mexico", "NM"],
    ["New York", "NY"],
    ["North Carolina", "NC"],
    ["North Dakota", "ND"],
    ["Ohio", "OH"],
    ["Oklahoma", "OK"],
    ["Oregon", "OR"],
    ["Pennsylvania", "PA"],
    ["Rhode Island", "RI"],
    ["South Carolina", "SC"],
    ["South Dakota", "SD"],
    ["Tennessee", "TN"],
    ["Texas", "TX"],
    ["Utah", "UT"],
    ["Vermont", "VT"],
    ["Virginia", "VA"],
    ["Washington", "WA"],
    ["West Virginia", "WV"],
    ["Wisconsin", "WI"],
    ["Wyoming", "WY"]
]);

const jsToSqlFilters = new Map([
    ["name", "t.name"],
    ["state", "t.state"],
    ["city", "t.city"],
    ["difficulty", "t.difficulty"],
    ["dogsAllowed", "t.dogs_allowed"],
    ["description", "t.description"],
    ["landManager", "t.land_manager"],
    ["type", "ts.type"],
    ["minDistanceImperial", "ts.distance_imperial"],
    ["maxDistanceImperial", "ts.distance_imperial"],
    ["minDistanceMetric", "ts.distance_metric"],
    ["maxDistanceMetric", "ts.distance_metric"],
    ["maxElevationImperial", "ts.elevation_high_imperial"],
    ["minElevationImperial", "ts.elevation_low_imperial"],
    ["maxElevationMetric", "ts.elevation_high_metric"],
    ["minElevationMetric", "ts.elevation_low_metric"],
    ["maxElevationLossImperial", "ts.elevation_loss_imperial"],
    ["minElevationLossMetric", "ts.elevation_loss_metric"],
    ["maxElevationGainImperial", "ts.elevation_gain_imperial"],
    ["minElevationGainMetric", "ts.elevation_gain_metric"],
    ["minAvgGradeDegree", "ts.avg_grade_degree"],
    ["maxAvgGradeDegree", "ts.avg_grade_degree"],
    ["minAvgGradePercent", "ts.avg_grade_percent"],
    ["maxAvgGradePercent", "ts.avg_grade_percent"],
    ["maxGradePercent", "ts.max_grade_percent"],
    ["maxGradeDegree", "ts.max_grade_degree"],
    ["rating", "r.rating"]
]);


module.exports = {
    states,
    jsToSqlFilters,
}