DROP DATABASE "trail_wanderer_test";

CREATE DATABASE "trail_wanderer_test";

\c "trail_wanderer_test";

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(25) UNIQUE NOT NULL,
  "password_hash" varchar(100), --Only for locally created users.
  "first_name" varchar(30) NOT NULL,
  "last_name" varchar(30) NOT NULL,
  "email" varchar(60) NOT NULL,
  "profile_image_path" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "active" boolean NOT NULL DEFAULT TRUE,
  "acct_type" varchar(10)
);

CREATE TABLE oauth_providers (
    "id" SERIAL PRIMARY KEY,
    "user_id" INT,
    "provider_name" VARCHAR(255),
    "provider_user_id" VARCHAR(255),
    "access_token" TEXT,
    "refresh_token" TEXT,
    "token_expiry" TIMESTAMPTZ,  -- Expiry date of the access token
    "created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE TABLE "completed_trails" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "trail_id" integer NOT NULL,
  "date_completed" date,
  "image_path" text, --remove
  "is_favorite" boolean NOT NULL DEFAULT FALSE --remove
);

CREATE TABLE "wanted_trails" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "trail_id" integer NOT NULL
);

CREATE TABLE "trails" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "city" varchar(100),
  "state" varchar(2),
  "difficulty" varchar(50),
  "dogs_allowed" varchar(50),
  "description" text,
  "land_manager" text
);

CREATE TABLE "trail_images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trail_id" integer NOT NULL,
  "path" varchar(255)
);

CREATE TABLE "trail_stats" (
  "trail_id" integer NOT NULL PRIMARY KEY,
  "type" varchar(50),
  "distance_imperial" float,
  "distance_metric" float,
  "elevation_high_imperial" float,
  "elevation_high_metric" float,
  "elevation_low_imperial" float,
  "elevation_low_metric" float,
  "elevation_gain_imperial" float,
  "elevation_gain_metric" float,
  "elevation_loss_imperial" float,
  "elevation_loss_metric" float,
  "avg_grade_percent" float,
  "avg_grade_degree" float,
  "max_grade_percent" float,
  "max_grade_degree" float
);

CREATE TABLE "features" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "feature_name" varchar(100)
);

CREATE TABLE "trail_features" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "feature_id" integer NOT NULL,
  "trail_id" integer NOT NULL
);

CREATE TABLE "ratings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trail_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "rating" float
);

--postgis must be installed and enabled
--sudo apt-get install postgresql-postgis-3
--CREATE EXTENSION postgis;
CREATE TABLE "trail_polylines" (
  trail_id INTEGER PRIMARY KEY,
  polyline GEOMETRY(LINESTRING, 4326),
  FOREIGN KEY (trail_id) REFERENCES trails(id) ON DELETE CASCADE
);



ALTER TABLE "completed_trails" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "completed_trails" ADD FOREIGN KEY ("trail_id") REFERENCES "trails" ("id");

ALTER TABLE "wanted_trails" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "wanted_trails" ADD FOREIGN KEY ("trail_id") REFERENCES "trails" ("id");

ALTER TABLE "trail_images" ADD FOREIGN KEY ("trail_id") REFERENCES "trails" ("id");

ALTER TABLE "trail_stats" ADD FOREIGN KEY ("trail_id") REFERENCES "trails" ("id");

ALTER TABLE "trail_features" ADD FOREIGN KEY ("trail_id") REFERENCES "trails" ("id");

ALTER TABLE "trail_features" ADD FOREIGN KEY ("feature_id") REFERENCES "features" ("id");

ALTER TABLE "ratings" ADD FOREIGN KEY ("trail_id") REFERENCES "trails" ("id");

ALTER TABLE "ratings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "oauth_providers" ADD CONSTRAINT "unique_user_provider" UNIQUE ("user_id", "provider_name");

ALTER TABLE "users" ADD CONSTRAINT "unique_email" UNIQUE ("email");

INSERT INTO "trails"
("name","city","state","difficulty","dogs_allowed","description","land_manager")
VALUES
('Trail 1', 'Huntsville', 'AL', 'Easy', 'Unknown', 'Description 1', 'Manager 1'),
('Trail 2', 'Anchorage', 'AK', 'Moderate', 'Unknown', 'Description 2', 'Manager 2'),
('Trail 3', 'Phoenix', 'AZ', 'Difficult', 'Unknown', 'Description 3', 'Manager 3'),
('Trail 4', 'Little Rock', 'AR', 'Moderate', 'Unknown', 'Description 4', 'Manager 4'),
('Trail 5', 'Los Angeles', 'CA', 'Challenging', 'Unknown', 'Description 5', 'Manager 5'),
('Trail 6', 'Denver', 'CO', 'Hard', 'Unknown', 'Description 6', 'Manager 6'),
('Trail 7', 'Hartford', 'CT', 'Hard', 'Unknown', 'Description 7', 'Manager 7'),
('Trail 8', 'Dover', 'DE', 'Difficult', 'Unknown', 'Description 8', 'Manager 8'),
('Trail 9', 'Miami', 'FL', 'Moderate', 'Unknown', 'Description 9', 'Manager 9'),
('Trail 10', 'Atlanta', 'GA', 'Easy', 'Leashed', 'Description 10', 'Manager 10'),
('Trail 11', 'Honolulu', 'HI', 'Easy', 'Unknown', 'Description 11', 'Manager 11'),
('Trail 12', 'Boise', 'ID', 'Easy', 'No', 'Description 12', 'Manager 12'),
('Trail 13', 'Chicago', 'IL', 'Easy', 'No', 'Description 13', 'Manager 13'),
('Trail 14', 'Indianapolis', 'IN', 'Easy', 'Leashed', 'Description 14', 'Manager 14'),
('Trail 15', 'Des Moines', 'IA', 'Easy', 'Unknown', 'Description 15', 'Manager 15'),
('Trail 16', 'Wichita', 'KS', 'Easy', 'Unknown', 'Description 16', 'Manager 16'),
('Trail 17', 'Louisville', 'KY', 'Easy', 'Unknown', 'Description 17', 'Manager 17'),
('Trail 18', 'New Orleans', 'LA', 'Easy', 'Unknown', 'Description 18', 'Manager 18'),
('Trail 19', 'Portland', 'ME', 'Easy', 'Unknown', 'Description 19', 'Manager 19'),
('Trail 20', 'Baltimore', 'MD', 'Easy', 'Unknown', 'Description 20', 'Manager 20'),
('Trail 21', 'Boston', 'MA', 'Easy', 'Unknown', 'Description 21', 'Manager 21'),
('Trail 22', 'Detroit', 'MI', 'Easy', 'Unknown', 'Description 22', 'Manager 22'),
('Trail 23', 'Minneapolis', 'MN', 'Easy', 'Unknown', 'Description 23', 'Manager 23'),
('Trail 24', 'Jackson', 'MS', 'Easy', 'Unknown', 'Description 24', 'Manager 24'),
('Trail 25', 'Kansas City', 'MO', 'Easy', 'Unknown', 'Description 25', 'Manager 25'),
('Trail 26', 'Billings', 'MT', 'Easy', 'Unknown', 'Description 26', 'Manager 26'),
('Trail 27', 'Omaha', 'NE', 'Easy', 'Unknown', 'Description 27', 'Manager 27'),
('Trail 28', 'Las Vegas', 'NV', 'Easy', 'Unknown', 'Description 28', 'Manager 28'),
('Trail 29', 'Manchester', 'NH', 'Easy', 'Unknown', 'Description 29', 'Manager 29'),
('Trail 30', 'Newark', 'NJ', 'Easy', 'Unknown', 'Description 30', 'Manager 30'),
('Trail 31', 'Albuquerque', 'NM', 'Easy', 'Unknown', 'Description 31', 'Manager 31'),
('Trail 32', 'New York', 'NY', 'Easy', 'Unknown', 'Description 32', 'Manager 32'),
('Trail 33', 'Charlotte', 'NC', 'Easy', 'Unknown', 'Description 33', 'Manager 33'),
('Trail 34', 'Fargo', 'ND', 'Easy', 'Unknown', 'Description 34', 'Manager 34'),
('Trail 35', 'Columbus', 'OH', 'Easy', 'Unknown', 'Description 35', 'Manager 35'),
('Trail 36', 'Oklahoma City', 'OK', 'Easy', 'Unknown', 'Description 36', 'Manager 36'),
('Trail 37', 'Portland', 'OR', 'Easy', 'Unknown', 'Description 37', 'Manager 37'),
('Trail 38', 'Philadelphia', 'PA', 'Easy', 'Unknown', 'Description 38', 'Manager 38'),
('Trail 39', 'Providence', 'RI', 'Easy', 'Unknown', 'Description 39', 'Manager 39'),
('Trail 40', 'Charleston', 'SC', 'Easy', 'Unknown', 'Description 40', 'Manager 40'),
('Trail 41', 'Sioux Falls', 'SD', 'Easy', 'Unknown', 'Description 41', 'Manager 41'),
('Trail 42', 'Nashville', 'TN', 'Easy', 'Unknown', 'Description 42', 'Manager 42'),
('Trail 43', 'Houston', 'TX', 'Easy', 'Unknown', 'Description 43', 'Manager 43'),
('Trail 44', 'Salt Lake City', 'UT', 'Easy', 'Unknown', 'Description 44', 'Manager 44'),
('Trail 45', 'Burlington', 'VT', 'Easy', 'Unknown', 'Description 45', 'Manager 45'),
('Trail 46', 'Virginia Beach', 'VA', 'Easy', 'Unknown', 'Description 46', 'Manager 46'),
('Trail 47', 'Seattle', 'WA', 'Easy', 'Unknown', 'Description 47', 'Manager 47'),
('Trail 48', 'Charleston', 'WV', 'Easy', 'Unknown', 'Description 48', 'Manager 48'),
('Trail 49', 'Milwaukee', 'WI', 'Easy', 'Unknown', 'Description 49', 'Manager 49'),
('Trail 50', 'Cheyenne', 'WY', 'Easy', 'Unknown', 'Description 50', 'Manager 50');

INSERT INTO trail_stats
(trail_id, type, distance_imperial, distance_metric, elevation_high_imperial, elevation_high_metric, elevation_low_imperial, elevation_low_metric, elevation_gain_imperial, elevation_gain_metric, elevation_loss_imperial, elevation_loss_metric, avg_grade_percent, avg_grade_degree, max_grade_percent, max_grade_degree)
VALUES
(1, 'Loop', 3.5, 5.6, 1200, 365.8, 800, 243.8, 400, 121.9, 200, 60.9, 5, 2.86, 10, 5.71),
(2, 'Out & Back', 4.2, 6.8, 1500, 457.2, 1000, 304.8, 500, 152.4, 250, 76.2, 6, 3.43, 12, 6.86),
(3, 'Loop', 2.9, 4.7, 1100, 335.3, 700, 213.4, 400, 121.9, 200, 60.9, 5.5, 3.14, 11, 6.29),
(4, 'Point to Point', 5.3, 8.5, 1700, 518.2, 1300, 396.2, 400, 121.9, 300, 91.4, 7, 4.00, 13, 7.43),
(5, 'Loop', 3.8, 6.1, 1250, 381.0, 850, 259.1, 400, 121.9, 200, 60.9, 6, 3.43, 12, 6.86),
(6, 'Out & Back', 4.5, 7.2, 1400, 426.7, 900, 274.3, 500, 152.4, 250, 76.2, 6.5, 3.71, 13, 7.43),
(7, 'Loop', 2.7, 4.3, 1050, 320.0, 650, 198.1, 400, 121.9, 200, 60.9, 5, 2.86, 10, 5.71),
(8, 'Point to Point', 5.8, 9.3, 1800, 548.6, 1400, 426.7, 400, 121.9, 300, 91.4, 7.5, 4.29, 14, 8.00),
(9, 'Loop', 3.3, 5.3, 1200, 365.8, 800, 243.8, 400, 121.9, 200, 60.9, 5.5, 3.14, 11, 6.29),
(10, 'Out & Back', 4.7, 7.6, 1450, 442.0, 950, 289.6, 500, 152.4, 250, 76.2, 6.5, 3.71, 13, 7.43),
(11, 'Loop', 3.1, 5.0, 1150, 350.5, 750, 228.6, 400, 121.9, 200, 60.9, 6, 3.43, 12, 6.86),
(12, 'Point to Point', 6.0, 9.7, 1900, 579.1, 1500, 457.2, 400, 121.9, 300, 91.4, 8, 4.57, 15, 8.57),
(13, 'Loop', 3.6, 5.8, 1300, 396.2, 850, 259.1, 450, 137.2, 200, 60.9, 5, 2.86, 10, 5.71),
(14, 'Out & Back', 4.9, 7.9, 1600, 487.7, 1000, 304.8, 600, 182.9, 250, 76.2, 6.5, 3.71, 13, 7.43),
(15, 'Loop', 2.8, 4.5, 1080, 329.2, 680, 207.3, 400, 121.9, 200, 60.9, 6, 3.43, 12, 6.86),
(16, 'Point to Point', 6.2, 10.0, 2000, 609.6, 1600, 487.7, 400, 121.9, 300, 91.4, 7.5, 4.29, 14, 8.00),
(17, 'Loop', 3.9, 6.3, 1350, 411.5, 900, 274.3, 450, 137.2, 200, 60.9, 5.5, 3.14, 11, 6.29),
(18, 'Out & Back', 5.2, 8.4, 1700, 518.2, 1100, 335.3, 600, 182.9, 250, 76.2, 6.5, 3.71, 13, 7.43),
(19, 'Loop', 3.5, 5.6, 1250, 381.0, 800, 243.8, 450, 137.2, 200, 60.9, 5, 2.86, 10, 5.71),
(20, 'Point to Point', 6.5, 10.5, 2100, 640.1, 1700, 518.2, 400, 121.9, 300, 91.4, 8, 4.57, 15, 8.57),
(21, 'Loop', 4.0, 6.4, 1400, 426.7, 950, 289.6, 450, 137.2, 200, 60.9, 6, 3.43, 12, 6.86),
(22, 'Out & Back', 5.4, 8.7, 1750, 533.4, 1150, 350.5, 600, 182.9, 250, 76.2, 6.5, 3.71, 13, 7.43),
(23, 'Loop', 3.7, 6.0, 1300, 396.2, 850, 259.1, 450, 137.2, 200, 60.9, 5.5, 3.14, 11, 6.29),
(24, 'Point to Point', 6.8, 10.9, 2200, 670.6, 1800, 548.6, 400, 121.9, 300, 91.4, 7.5, 4.29, 14, 8.00),
(25, 'Loop', 4.2, 6.8, 1500, 457.2, 1000, 304.8, 500, 152.4, 200, 60.9, 6, 3.43, 12, 6.86),
(26, 'Out & Back', 5.7, 9.2, 1850, 563.9, 1250, 381.0, 600, 182.9, 250, 76.2, 6.5, 3.71, 13, 7.43),
(27, 'Loop', 4.4, 7.1, 1550, 472.4, 1050, 320.0, 500, 152.4, 200, 60.9, 5, 2.86, 10, 5.71),
(28, 'Point to Point', 7.0, 11.3, 2300, 701.0, 1900, 579.1, 400, 121.9, 300, 91.4, 8, 4.57, 15, 8.57),
(29, 'Loop', 4.6, 7.4, 1600, 487.7, 1100, 335.3, 500, 152.4, 200, 60.9, 5.5, 3.14, 11, 6.29),
(30, 'Out & Back', 6.0, 9.7, 1950, 594.4, 1300, 396.2, 650, 198.1, 250, 76.2, 6.5, 3.71, 13, 7.43),
(31, 'Loop', 4.8, 7.7, 1650, 502.9, 1150, 350.5, 500, 152.4, 200, 60.9, 6, 3.43, 12, 6.86),
(32, 'Point to Point', 7.3, 11.7, 2400, 731.5, 2000, 609.6, 400, 121.9, 300, 91.4, 8, 4.57, 15, 8.57),
(33, 'Loop', 5.0, 8.0, 1700, 518.2, 1200, 365.8, 500, 152.4, 200, 60.9, 5.5, 3.14, 11, 6.29),
(34, 'Out & Back', 6.2, 10.0, 2000, 609.6, 1350, 411.5, 650, 198.1, 250, 76.2, 6.5, 3.71, 13, 7.43),
(35, 'Loop', 5.2, 8.4, 1750, 533.4, 1250, 381.0, 500, 152.4, 200, 60.9, 6, 3.43, 12, 6.86),
(36, 'Point to Point', 7.5, 12.1, 2500, 762.0, 2100, 640.1, 400, 121.9, 300, 91.4, 8, 4.57, 15, 8.57),
(37, 'Loop', 5.4, 8.7, 1800, 548.6, 1300, 396.2, 500, 152.4, 200, 60.9, 5.5, 3.14, 11, 6.29),
(38, 'Out & Back', 6.5, 10.5, 2100, 640.1, 1400, 426.7, 700, 213.4, 250, 76.2, 6.5, 3.71, 13, 7.43),
(39, 'Loop', 5.6, 9.0, 1850, 563.9, 1350, 411.5, 500, 152.4, 200, 60.9, 6, 3.43, 12, 6.86),
(40, 'Point to Point', 7.8, 12.6, 2600, 792.5, 2200, 670.6, 400, 121.9, 300, 91.4, 8, 4.57, 15, 8.57),
(41, 'Loop', 5.8, 9.3, 1900, 579.1, 1400, 426.7, 500, 152.4, 200, 60.9, 5.5, 3.14, 11, 6.29),
(42, 'Out & Back', 6.7, 10.8, 2200, 670.6, 1450, 442.0, 750, 228.6, 250, 76.2, 6.5, 3.71, 13, 7.43),
(43, 'Loop', 6.0, 9.7, 1950, 594.4, 1500, 457.2, 500, 152.4, 200, 60.9, 6, 3.43, 12, 6.86),
(44, 'Point to Point', 8.0, 12.9, 2700, 823.0, 2300, 701.0, 400, 121.9, 300, 91.4, 8, 4.57, 15, 8.57),
(45, 'Loop', 6.2, 10.0, 2000, 609.6, 1550, 472.4, 500, 152.4, 200, 60.9, 5.5, 3.14, 11, 6.29),
(46, 'Out & Back', 7.0, 11.3, 2300, 701.0, 1600, 487.7, 700, 213.4, 250, 76.2, 6.5, 3.71, 13, 7.43),
(47, 'Loop', 6.4, 10.3, 2050, 624.8, 1600, 487.7, 500, 152.4, 200, 60.9, 6, 3.43, 12, 6.86),
(48, 'Point to Point', 8.3, 13.4, 2800, 853.4, 2400, 731.5, 400, 121.9, 300, 91.4, 8, 4.57, 15, 8.57),
(49, 'Loop', 6.6, 10.6, 2100, 640.1, 1650, 502.9, 500, 152.4, 200, 60.9, 5.5, 3.14, 11, 6.29),
(50, 'Out & Back', 7.2, 11.6, 2400, 731.5, 1700, 518.2, 700, 213.4, 250, 76.2, 6.5, 3.71, 13, 7.43);

INSERT INTO features (feature_name)
VALUES
('Cave'),
('Waterfall'),
('Wildflowers'),
('Birding'),
('Fall Colors'),
('River/Creek'),
('Swimming'),
('Views'),
('Lake'),
('Fishing'),
('Hot Spring');


INSERT INTO trail_features (trail_id, feature_id)
VALUES
(1, 1), (1, 2), (1, 3),
(2, 2), (2, 4),
(3, 3), (3, 5), (3, 6),
(4, 4), (4, 7),
(5, 5), (5, 8), (5, 9),
(6, 6), (6, 10),
(7, 7), (7, 11),
(8, 8), (8, 1), (8, 2),
(9, 9), (9, 3),
(10, 10), (10, 4), (10, 5),
(11, 11), (11, 6),
(12, 1), (12, 7),
(13, 2), (13, 8), (13, 9),
(14, 3), (14, 10),
(15, 4), (15, 11),
(16, 5), (16, 1), (16, 2),
(17, 6), (17, 3),
(18, 7), (18, 4), (18, 5),
(19, 8), (19, 6),
(20, 9), (20, 7),
(21, 10), (21, 8), (21, 9),
(22, 11), (22, 10),
(23, 1), (23, 11),
(24, 2), (24, 1), (24, 3),
(25, 3), (25, 2),
(26, 4), (26, 5), (26, 6),
(27, 5), (27, 7),
(28, 6), (28, 8), (28, 9),
(29, 7), (29, 10),
(30, 8), (30, 11),
(31, 9), (31, 1), (31, 2),
(32, 10), (32, 3),
(33, 11), (33, 4), (33, 5),
(34, 1), (34, 6),
(35, 2), (35, 7),
(36, 3), (36, 8), (36, 9),
(37, 4), (37, 10),
(38, 5), (38, 11),
(39, 6), (39, 1), (39, 2),
(40, 7), (40, 3),
(41, 8), (41, 4), (41, 5),
(42, 9), (42, 6),
(43, 10), (43, 7),
(44, 11), (44, 8), (44, 9),
(45, 1), (45, 10),
(46, 2), (46, 11),
(47, 3), (47, 1), (47, 2),
(48, 4), (48, 3),
(49, 5), (49, 4), (49, 6),
(50, 6), (50, 7); 